### ISSUE TITLE
master branch cannot build

### ISSUE THREAD

**Issue by wjaspers** [crypto-rb/rbnacl-libsodium#30]
v1.0.16 works correctly; but the output target doesn't match any vendor folders

*System*
ruby 2.3.3 rvm on OSX 10.13

```sh
Using rbnacl-libsodium 1.0.16 from ssh://git@github.com/crypto-rb/rbnacl-libsodium.git (at master@c1ee4d6)
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/myusername/.rvm/gems/ruby-2.3.3@my-project/bundler/gems/rbnacl-libsodium-c1ee4d621b2e/ext/rbnacl
/Users/myusername/.rvm/rubies/ruby-2.3.3/bin/ruby -r ./siteconf20181102-67077-1gap4st.rb extconf.rb
 -- sh -c "./configure --prefix=/Users/myusername/.rvm/gems/ruby-2.3.3@my-project/bundler/gems/rbnacl-libsodium-c1ee4d621b2e/vendor/libsodium/dist "
sh: ./configure: No such file or directory
extconf.rb:8:in `sys': ERROR: 'sh -c "./configure --prefix=/Users/myusername/.rvm/gems/ruby-2.3.3@my-project/bundler/gems/rbnacl-libsodium-c1ee4d621b2e/vendor/libsodium/dist "' failed (RuntimeError)
	from extconf.rb:36:in `block in <main>'
	from extconf.rb:34:in `chdir'
	from extconf.rb:34:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Users/myusername/.rvm/gems/ruby-2.3.3@my-project/bundler/gems/rbnacl-libsodium-c1ee4d621b2e for inspection.
Results logged to /Users/myusername/.rvm/gems/ruby-2.3.3@my-project/bundler/gems/extensions/x86_64-darwin-16/2.3.0/rbnacl-libsodium-c1ee4d621b2e/gem_make.out

An error occurred while installing rbnacl-libsodium (1.0.16), and Bundler cannot continue.

In Gemfile:
  rbnacl-libsodium
```

**Comment by wjaspers** [comment]
related commit in a fork of this project:
https://github.com/steveklebanoff/rbnacl-libsodium/commit/6e720c884d5e2d97247fa72e60fbbb20c8510ce9#diff-a4536f768b03bdf4c4ec95454620107b

**Comment by tarcieri** [comment]
You can open a PR, although #29 I would like to deprecate this gem.

**Comment by wjaspers** [comment]
I forgot to run this with automake installed; whoops.
